version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end