version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: ubuntu:latest
    ports:
      - "5252"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "9000"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend